Update update-submodules.yml

diff --git a/.github/workflows/update-submodules.yml b/.github/workflows/update-submodules.yml
--- a/.github/workflows/update-submodules.yml
+++ b/.github/workflows/update-submodules.yml
@@ -1,43 +1,75 @@
----
-name: Update submodules!
+name: Update Submodules
 
-#############################
-# Start the job on all push #
-#############################
 on:
-  schedule:
-    - cron: "0 0 */7 * *"
   workflow_dispatch:
 
-###############
-# Set the Job #
-###############
 jobs:
-  build:
-    name: Update submodules
+  update-submodules:
     runs-on: ubuntu-latest
-    env:
-      PARENT_REPOSITORY: 'qnblackcat/uYouPlus'
-      CHECKOUT_BRANCH: 'main'
-      PR_AGAINST_BRANCH: 'main'
-      OWNER: 'qnblackcat'
 
     steps:
-      ##########################
-      # Checkout the code base #
-      ##########################
-      - name: Checkout Code
-        uses: actions/checkout@v3
+      - name: Checkout code
+        uses: actions/checkout@v3.5.3
 
-      ####################################
-      # Run the action against code base #
-      ####################################
-      - name: run action
-        id: run_action
-        uses: qnblackcat/github-action-create-pr-parent-submodule@main
-        with:
-          github_token: ${{ secrets.RELEASE_HUB_SECRET }}
-          parent_repository: ${{ env.PARENT_REPOSITORY }}
-          checkout_branch: ${{ env.CHECKOUT_BRANCH }}
-          pr_against_branch: ${{ env.PR_AGAINST_BRANCH }}
-          owner: ${{ env.OWNER }}
+      - name: Set up Git
+        run: |
+           git config --global user.email "actions@github.com"
+           git config --global user.name "GitHub Actions"
+
+      - name: Added YTNoCommunityPosts submodule
+        run: |
+          git submodule add https://github.com/michael-winay/YTNoCommunityPosts.git Tweaks/YTNoCommunityPosts
+          git add .
+          git commit -m "added YTNoCommunityPosts submodule"
+          git push origin
+
+      - name: Update submodules
+        run: |
+          git submodule update --init --recursive --remote Tweaks/Alderis
+          git add .
+          git submodule update --init --recursive --remote Tweaks/DontEatMyContent
+          git add .
+          git submodule update --init --recursive --remote Tweaks/PSHeader
+          git add .
+          git submodule update --init --recursive --remote Tweaks/Return-YouTube-Dislikes
+          git add .
+          git submodule update --init --recursive --remote Tweaks/YTABConfig
+          git add .
+          git submodule update --init --recursive --remote Tweaks/YTNoCommunityPosts
+          git add .
+          git submodule update --init --recursive --remote Tweaks/YTUHD
+          git add .
+          git submodule update --init --recursive --remote Tweaks/YTVideoOverlay
+          git add .
+          git submodule update --init --recursive --remote Tweaks/YouMute
+          git add .
+          git submodule update --init --recursive --remote Tweaks/YouPiP
+          git add .
+          git submodule update --init --recursive --remote Tweaks/YouQuality
+          git add .
+          git submodule update --init --recursive --remote Tweaks/YouTubeHeader
+          git add .
+          git submodule update --init --recursive --remote Tweaks/iSponsorBlock
+          git add .
+          git commit -m "updated submodules"
+          git push origin
+        continue-on-error: true
+
+      - name: Make .bundle files
+        run: |
+          cd Bundles
+          ln -s ../Tweaks/YTVideoOverlay/layout/Library/Application\ Support/YTVideoOverlay.bundle YTVideoOverlay.bundle
+          ln -s ../Tweaks/YouMute/layout/Library/Application\ Support/YouMute.bundle YouMute.bundle
+          ln -s ../Tweaks/YouQuality/layout/Library/Application\ Support/YouQuality.bundle YouQuality.bundle
+          ln -s ../Tweaks/YTNoCommunityPosts/layout/Library/Application\ Support/YTNoCommunityPosts.bundle YTNoCommunityPosts.bundle
+          git add .
+          git commit -m "Added bundles"
+          git push origin
+
+      - name: Check exit code
+        run: |
+          exit_code=$?
+          if [ $exit_code -ne 0 ]; then
+            echo "Submodule update failed with exit code $exit_code"
+            exit 1
+          fi
